### ISSUE TITLE
cocoapods 搜不到该库 更新本地仓库之后 还是搜不到

### ISSUE THREAD

**Issue by haijiaoliuhao91** [boai/BAPrivacyManager#3]

**Comment by boai** [comment]
@haijiaoliuhao91 你直接pod update，然后看下更新下来的版本是多少？我这边刚建了新demo试了没问题，可以用。

**Comment by haijiaoliuhao91** [comment]
@boai [!] Unable to find a pod with name, author, summary, or description matching `BAPrivacyManager`, 我是直接就搜不到这个库, 你其他的库我都可以搜得到, 只有这个搜不到

**Comment by boai** [comment]
你加我QQ 137361770

**Comment by haijiaoliuhao91** [comment]
Thank you very much
